/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.teamneko.schrodinger.backend.gui;

import javax.swing.JOptionPane;

import org.teamneko.meowlib.dto.TransactionRequest;
import org.teamneko.schrodinger.client.SchrodingerClient;

/**
 *
 * @author Alexandre
 */

 
public class main_window extends javax.swing.JFrame {
	private ProductListModel products = new ProductListModel();
	private SchrodingerClient client = new SchrodingerClient("http://localhost:8080/rest");
	
    /**
     * Creates new form main_window
     */
    public main_window() {
        initComponents();
        this.addKeyListener(new BarcodeScannerController());
        jTextField_barcode.requestFocus();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Button_control = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton_plus = new javax.swing.JButton();
        jButton_down = new javax.swing.JButton();
        jButton_up = new javax.swing.JButton();
        jButton_minus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton_cancel = new javax.swing.JButton();
        jButton_ok = new javax.swing.JButton();
        jPanel_options = new javax.swing.JPanel();
        jButton_deco = new javax.swing.JButton();
        jButton_shutdown = new javax.swing.JButton();
        jButton_clavier = new javax.swing.JButton();
        jButton_clavier_annuler = new javax.swing.JButton();
        jPanel_Clavier = new javax.swing.JPanel();
        jButton_number_1 = new javax.swing.JButton();
        jButton_number_2 = new javax.swing.JButton();
        jButton_number_3 = new javax.swing.JButton();
        jButton_number_4 = new javax.swing.JButton();
        jButton_number_5 = new javax.swing.JButton();
        jButton_number_6 = new javax.swing.JButton();
        jButton_number_7 = new javax.swing.JButton();
        jButton_number_8 = new javax.swing.JButton();
        jButton_number_9 = new javax.swing.JButton();
        jButton_number_0 = new javax.swing.JButton();
        jButton_number_cancel = new javax.swing.JButton();
        jPanel_auth = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Main = new javax.swing.JPanel();
        jSplitPane = new javax.swing.JSplitPane();
        jPanel_Button = new javax.swing.JPanel();
        jButton_modifier = new javax.swing.JButton();
        jButton_options = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_view = new javax.swing.JPanel();
        jTextField_barcode = new javax.swing.JTextField();
        jLabel_type = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_items = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jPanel_Button_control.setPreferredSize(new java.awt.Dimension(133, 320));

        jButton_plus.setText("+");
        jButton_plus.setAlignmentY(0.0F);
        jButton_plus.setFocusable(false);
        jButton_plus.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_plusActionPerformed(evt);
            }
        });

        jButton_down.setText("▼");
        jButton_down.setFocusable(false);
        jButton_down.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_downActionPerformed(evt);
            }
        });

        jButton_up.setText("▲");
        jButton_up.setAlignmentY(0.0F);
        jButton_up.setFocusable(false);
        jButton_up.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_upMouseClicked(evt);
            }
        });
        jButton_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_upActionPerformed(evt);
            }
        });

        jButton_minus.setText("-");
        jButton_minus.setFocusable(false);
        jButton_minus.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_down, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton_up, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_minus, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton_plus, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_down, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton_cancel.setText("Annuler");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jButton_ok.setText("Ok");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_ok, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_Button_controlLayout = new javax.swing.GroupLayout(jPanel_Button_control);
        jPanel_Button_control.setLayout(jPanel_Button_controlLayout);
        jPanel_Button_controlLayout.setHorizontalGroup(
            jPanel_Button_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Button_controlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Button_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel_Button_controlLayout.setVerticalGroup(
            jPanel_Button_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Button_controlLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jButton_deco.setText("Déconnexion");
        jButton_deco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_decoActionPerformed(evt);
            }
        });

        jButton_shutdown.setText("Mise Hors Tension");
        jButton_shutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_shutdownActionPerformed(evt);
            }
        });

        jButton_clavier.setText("Clavier Numérique");
        jButton_clavier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clavierActionPerformed(evt);
            }
        });

        jButton_clavier_annuler.setText("Annuler");
        jButton_clavier_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clavier_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_optionsLayout = new javax.swing.GroupLayout(jPanel_options);
        jPanel_options.setLayout(jPanel_optionsLayout);
        jPanel_optionsLayout.setHorizontalGroup(
            jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_clavier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_deco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_shutdown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_clavier_annuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        jPanel_optionsLayout.setVerticalGroup(
            jPanel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_clavier, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_deco, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_shutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_clavier_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel_Clavier.setFocusable(false);
        jPanel_Clavier.setPreferredSize(new java.awt.Dimension(133, 320));

        jButton_number_1.setText("1");
        jButton_number_1.setFocusable(false);
        jButton_number_1.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_1.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton_number_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_1ActionPerformed(evt);
            }
        });

        jButton_number_2.setText("2");
        jButton_number_2.setFocusable(false);
        jButton_number_2.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_2.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_2ActionPerformed(evt);
            }
        });

        jButton_number_3.setText("3");
        jButton_number_3.setFocusable(false);
        jButton_number_3.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_3.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_3ActionPerformed(evt);
            }
        });

        jButton_number_4.setText("4");
        jButton_number_4.setFocusable(false);
        jButton_number_4.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_4.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_4ActionPerformed(evt);
            }
        });

        jButton_number_5.setText("5");
        jButton_number_5.setFocusable(false);
        jButton_number_5.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_5.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_5ActionPerformed(evt);
            }
        });

        jButton_number_6.setText("6");
        jButton_number_6.setFocusable(false);
        jButton_number_6.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_6.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_6ActionPerformed(evt);
            }
        });

        jButton_number_7.setText("7");
        jButton_number_7.setFocusable(false);
        jButton_number_7.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_7.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_7ActionPerformed(evt);
            }
        });

        jButton_number_8.setText("8");
        jButton_number_8.setFocusable(false);
        jButton_number_8.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_8.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_8ActionPerformed(evt);
            }
        });

        jButton_number_9.setText("9");
        jButton_number_9.setFocusable(false);
        jButton_number_9.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_9.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_9ActionPerformed(evt);
            }
        });

        jButton_number_0.setText("0");
        jButton_number_0.setFocusable(false);
        jButton_number_0.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton_number_0.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton_number_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_0ActionPerformed(evt);
            }
        });

        jButton_number_cancel.setText("Annuler");
        jButton_number_cancel.setFocusable(false);
        jButton_number_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_number_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ClavierLayout = new javax.swing.GroupLayout(jPanel_Clavier);
        jPanel_Clavier.setLayout(jPanel_ClavierLayout);
        jPanel_ClavierLayout.setHorizontalGroup(
            jPanel_ClavierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClavierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ClavierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_number_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_ClavierLayout.createSequentialGroup()
                        .addGroup(jPanel_ClavierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ClavierLayout.createSequentialGroup()
                                .addGroup(jPanel_ClavierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_number_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_ClavierLayout.createSequentialGroup()
                                        .addComponent(jButton_number_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_number_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_number_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_ClavierLayout.createSequentialGroup()
                                .addComponent(jButton_number_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_number_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_number_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_ClavierLayout.createSequentialGroup()
                                .addComponent(jButton_number_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_number_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_number_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel_ClavierLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_number_0, jButton_number_1, jButton_number_2, jButton_number_3, jButton_number_4, jButton_number_5, jButton_number_6, jButton_number_7, jButton_number_8, jButton_number_9});

        jPanel_ClavierLayout.setVerticalGroup(
            jPanel_ClavierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClavierLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel_ClavierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_number_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_number_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_number_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ClavierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_number_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_number_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_number_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ClavierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_number_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_number_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_number_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_number_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton_number_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_ClavierLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_number_0, jButton_number_1, jButton_number_2, jButton_number_3, jButton_number_4, jButton_number_5, jButton_number_6, jButton_number_7, jButton_number_8, jButton_number_9});

        jLabel2.setText("Place holder");

        javax.swing.GroupLayout jPanel_authLayout = new javax.swing.GroupLayout(jPanel_auth);
        jPanel_auth.setLayout(jPanel_authLayout);
        jPanel_authLayout.setHorizontalGroup(
            jPanel_authLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_authLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel_authLayout.setVerticalGroup(
            jPanel_authLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_authLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(480, 320));

        jPanel_Main.setMaximumSize(new java.awt.Dimension(480, 320));
        jPanel_Main.setMinimumSize(new java.awt.Dimension(480, 320));
        jPanel_Main.setPreferredSize(new java.awt.Dimension(480, 320));

        jSplitPane.setPreferredSize(new java.awt.Dimension(480, 320));

        jButton_modifier.setText("Modifier");
        jButton_modifier.setMaximumSize(new java.awt.Dimension(87, 23));
        jButton_modifier.setMinimumSize(new java.awt.Dimension(87, 23));
        jButton_modifier.setPreferredSize(new java.awt.Dimension(87, 23));
        jButton_modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_modifierMouseClicked(evt);
            }
        });
        jButton_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modifierActionPerformed(evt);
            }
        });

        jButton_options.setText("Paramètres");
        jButton_options.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_optionsMouseClicked(evt);
            }
        });
        jButton_options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_optionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ButtonLayout = new javax.swing.GroupLayout(jPanel_Button);
        jPanel_Button.setLayout(jPanel_ButtonLayout);
        jPanel_ButtonLayout.setHorizontalGroup(
            jPanel_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_ButtonLayout.createSequentialGroup()
                        .addComponent(jButton_options, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel_ButtonLayout.setVerticalGroup(
            jPanel_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ButtonLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton_options, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(jPanel_Button);

        jPanel_view.setMaximumSize(new java.awt.Dimension(340, 320));
        jPanel_view.setMinimumSize(new java.awt.Dimension(340, 320));
        jPanel_view.setPreferredSize(new java.awt.Dimension(340, 320));
        jTextField_barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_barcodeActionPerformed(evt);
            }
        });

        jLabel_type.setText("Type: Étagère");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/teamneko/schrodinger/backend/gui/myimageapp/-Barcode_32896.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jTable_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Patate",  new Integer(10000),  new Integer(0)},
                { new Integer(2), "orange",  new Integer(5),  new Integer(0)},
                { new Integer(3), "tangerine",  new Integer(400),  new Integer(0)},
                { new Integer(4), "concombre",  new Integer(52),  new Integer(0)}
            },
            new String [] {
                "# Item", "Nom", "Qty Actuelle", "Qty Modifié"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_items.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable_items);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton1.setText("C");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_viewLayout = new javax.swing.GroupLayout(jPanel_view);
        jPanel_view.setLayout(jPanel_viewLayout);
        jPanel_viewLayout.setHorizontalGroup(
            jPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel_viewLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jTextField_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_viewLayout.setVerticalGroup(
            jPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_type)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(jPanel_view);

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modifierActionPerformed
        
    	jSplitPane.setLeftComponent(jPanel_Button_control);
        jTextField_barcode.setEnabled(false);
        jTable_items.requestFocus();
        jTable_items.changeSelection(0, 0, false, false);
    }//GEN-LAST:event_jButton_modifierActionPerformed

    private void jTextField_barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_barcodeActionPerformed

    private void jButton_modifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_modifierMouseClicked
         jSplitPane.setLeftComponent(jPanel_Button_control);
    }//GEN-LAST:event_jButton_modifierMouseClicked

    private void jButton_optionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_optionsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_optionsMouseClicked

    private void jButton_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_upMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_upMouseClicked

    private void jButton_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_upActionPerformed
        jTable_items.requestFocusInWindow();
        int row = jTable_items.getSelectedRow();
        if(row > 0)
        {
            row--;
            jTable_items.setRowSelectionInterval(row, row);
        }
    }//GEN-LAST:event_jButton_upActionPerformed

    private void jButton_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusActionPerformed
     int row = jTable_items.getSelectedRow();
        String value = jTable_items.getValueAt(row, 3).toString();
        int val = Integer.parseInt(value);
        int id = Integer.parseInt(jTable_items.getValueAt(row, 0).toString());
        this.products.removeOneItem(id);
        
        val--;
        
        jTable_items.setValueAt(val, row, 3);
    }//GEN-LAST:event_jButton_minusActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        String message = "Voici les changement éfecctué:"
                + "";
        String title = "Confirmation des changements effectué";
        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        
	    if (reply == JOptionPane.YES_OPTION)
	    {
	      jSplitPane.setLeftComponent(jPanel_Button);
	      TransactionRequest transaction = new TransactionRequest();
	      //Set User ID
	      //Set Box Barcode
	      transaction.setProductsAdded(products.getProductsAdded());
	      transaction.setProductsRemoved(products.getProductsRemoved());
	      client.postTransaction(transaction);
	      jTextField_barcode.setEnabled(true);
	    }
    }//GEN-LAST:event_jButton_okActionPerformed

    private void jButton_shutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_shutdownActionPerformed
        // Runtime runtime = Runtime.getRuntime();
	// Process proc = runtime.exec("shutdown -s -t 0");
	// System.exit(0);
    }//GEN-LAST:event_jButton_shutdownActionPerformed

    private void jButton_decoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_decoActionPerformed
        //jPanel_Main.remove(jSplitPane);
        //jPanel_Main.add(jPanel_auth);
    }//GEN-LAST:event_jButton_decoActionPerformed

    private void jButton_number_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_1ActionPerformed
           String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '1');
    }//GEN-LAST:event_jButton_number_1ActionPerformed

    private void jButton_number_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_0ActionPerformed
        String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '0');
    }//GEN-LAST:event_jButton_number_0ActionPerformed

    private void jButton_optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_optionsActionPerformed
        jSplitPane.setLeftComponent(jPanel_options);
    }//GEN-LAST:event_jButton_optionsActionPerformed

    private void jButton_clavierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clavierActionPerformed
        jSplitPane.setLeftComponent(jPanel_Clavier);
    }//GEN-LAST:event_jButton_clavierActionPerformed

    private void jButton_number_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_cancelActionPerformed
        jSplitPane.setLeftComponent(jPanel_Button);
    }//GEN-LAST:event_jButton_number_cancelActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        jSplitPane.setLeftComponent(jPanel_Button); 
        jTextField_barcode.setEnabled(true);
        jTextField_barcode.requestFocus();
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_clavier_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clavier_annulerActionPerformed
        jSplitPane.setLeftComponent(jPanel_Button); 
    }//GEN-LAST:event_jButton_clavier_annulerActionPerformed

    private void jButton_number_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_2ActionPerformed
        String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '2');
    }//GEN-LAST:event_jButton_number_2ActionPerformed

    private void jButton_number_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_3ActionPerformed
        String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '3');
    }//GEN-LAST:event_jButton_number_3ActionPerformed

    private void jButton_number_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_4ActionPerformed
       String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '4');
    }//GEN-LAST:event_jButton_number_4ActionPerformed

    private void jButton_number_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_5ActionPerformed
       String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '5');
    }//GEN-LAST:event_jButton_number_5ActionPerformed

    private void jButton_number_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_6ActionPerformed
      String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '6');
    }//GEN-LAST:event_jButton_number_6ActionPerformed

    private void jButton_number_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_7ActionPerformed
      String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '7');
    }//GEN-LAST:event_jButton_number_7ActionPerformed

    private void jButton_number_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_8ActionPerformed
      String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '8');
    }//GEN-LAST:event_jButton_number_8ActionPerformed

    private void jButton_number_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_number_9ActionPerformed
      String text = jTextField_barcode.getText();
           jTextField_barcode.setText( text + '9');
    }//GEN-LAST:event_jButton_number_9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           jTextField_barcode.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_plusActionPerformed
        int row = jTable_items.getSelectedRow();
        String value = jTable_items.getValueAt(row, 3).toString();
        int val = Integer.parseInt(value);
        val++;
        
        int id = Integer.parseInt(jTable_items.getValueAt(row, 0).toString());
        this.products.addOneItem(id);
        
        jTable_items.setValueAt(val, row, 3);
    }//GEN-LAST:event_jButton_plusActionPerformed

    private void jButton_downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_downActionPerformed
        jTable_items.requestFocusInWindow();
        int row = jTable_items.getSelectedRow();
        int maxrow = jTable_items.getModel().getRowCount();
        maxrow--;
        if((row >= 0) && (row < maxrow))
        {
            row++;
            jTable_items.setRowSelectionInterval(row, row);
        }
    }//GEN-LAST:event_jButton_downActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_clavier;
    private javax.swing.JButton jButton_clavier_annuler;
    private javax.swing.JButton jButton_deco;
    private javax.swing.JButton jButton_down;
    private javax.swing.JButton jButton_minus;
    private javax.swing.JButton jButton_modifier;
    private javax.swing.JButton jButton_number_0;
    private javax.swing.JButton jButton_number_1;
    private javax.swing.JButton jButton_number_2;
    private javax.swing.JButton jButton_number_3;
    private javax.swing.JButton jButton_number_4;
    private javax.swing.JButton jButton_number_5;
    private javax.swing.JButton jButton_number_6;
    private javax.swing.JButton jButton_number_7;
    private javax.swing.JButton jButton_number_8;
    private javax.swing.JButton jButton_number_9;
    private javax.swing.JButton jButton_number_cancel;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JButton jButton_options;
    private javax.swing.JButton jButton_plus;
    private javax.swing.JButton jButton_shutdown;
    private javax.swing.JButton jButton_up;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_type;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Button;
    private javax.swing.JPanel jPanel_Button_control;
    private javax.swing.JPanel jPanel_Clavier;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JPanel jPanel_auth;
    private javax.swing.JPanel jPanel_options;
    private javax.swing.JPanel jPanel_view;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTable jTable_items;
    private javax.swing.JTextField jTextField_barcode;
    // End of variables declaration//GEN-END:variables
}
